EduPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('auth/', include('authsys.urls')),
    path('', RedirectView.as_view(url='/main/my_companies'))
]

main/urls.py
from django.urls import path
from .views import *


app_name = 'main'

urlpatterns = [
    path('my_companies', my_companies, name='my_companies'),
    path('company_admin/<int:comp_user_id>', lambda: None),
    path('company_teacher/<int:comp_user_id>', lambda: None),
    path('company_student/<int:comp_user_id>', lambda: None),
    path('enter_company/<int:id>', enter_company, name='enter_company'),
    # path('enter_company/<int:id>', enter_company, name='enter_company'),
    # path('reenter_company/<int:index>', reenter_company, name='reenter_company'),
    path('change_role/<int:id>', change_role, name='change_role'),
    path('company/<int:id>/subjects', subjects, name='subjects'),

    path('company/<int:id>/edit_subject/<int:subject_id>', edit_subject, name='edit_subject'),
    path('company/<int:id>/create_subject', create_subject, name='create_subject'),
    path('company/<int:id>/delete_subject/<int:subject_id>', delete_subject, name='delete_subject'),

    path('company/<int:id>/groups', groups, name='groups')
]

main/models.py
from django.db import models
from authsys.models import UserProfile
import datetime
import calendar
import random
from main.tools.calc_module import optimize_price


# Create your models here.
class Company(models.Model):
    owner = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    name = models.CharField(max_length=60)
    description = models.TextField(max_length=1000, blank=True)

    C_t_min = models.IntegerField(default=0)  # %
    C_s_min = models.IntegerField(default=0)

    p_t_ser = models.FloatField(default=6)
    p_s_ser = models.FloatField(default=5)

    @property
    def students_amount(self):  # FIXME: wrong way
        # return Student.objects.count()
        return CompanyUser.objects.filter(company=self, role__name='student').count()

    def calculate_income(self):
        return sum(group.calculate_students_payment() for group in Group.objects.filter(course__subject__company=self))

    def calculate_spends(self):
        return sum(group.calculate_teacher_payment() for group in Group.objects.filter(course__subject__company=self))

    def calculate_income_last_month(self):
        return sum(group.calculate_students_payment(datetime.date.today()) for group in Group.objects.filter(course__subject__company=self))

    def calculate_spends_last_month(self):
        return sum(group.calculate_teacher_payment(datetime.date.today()) for group in Group.objects.filter(course__subject__company=self))

    def calculate_income_for_month(self, month: datetime.date):
        return sum(group.calculate_students_payment(month) for group in Group.objects.filter(course__subject__company=self))

    def calculate_spends_for_month(self, month: datetime.date):
        return sum(group.calculate_teacher_payment(month) for group in Group.objects.filter(course__subject__company=self))

    @property
    def courses(self):
        subjects = Subject.objects.filter(company=self)
        return Course.objects.filter(subject__in=subjects)

    @property
    def courses_amount(self):
        return len(self.courses)

    @property
    def groups(self):
        return Group.objects.filter(course__in=self.courses)

    @property
    def groups_amount(self):
        return len(self.groups)

    def __str__(self):
        return f'{self.name}'


class Role(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return f"{self.name}"


class CompanyUser(models.Model):
    userprofile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.PROTECT)
    date_join = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.userprofile} - {self.company} - {self.role}"


class Subject(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField(max_length=1000, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} ({self.company})"


class Course(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=1000, blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    teacher_payment = models.IntegerField(default=200)
    student_payment = models.IntegerField(default=350)
    complexity = models.IntegerField(default=80)

    def __str__(self):
        return f"{self.name} ({self.subject})"


class Group(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=1000, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def calculate_students_payment(self, month: datetime.date=None):
        if month:
            lessons = Lesson.objects.filter(
                date_start__gte=datetime.date(month.year, month.month, 1),
                date_start__lte=datetime.date(month.year, month.month, calendar.monthrange(month.year, month.month)[1]),
                group=self
            )
        else:
            lessons = Lesson.objects.filter(group=self)
        return sum([lesson.calc_student_payment() * lesson.present_students.count() for lesson in lessons])

    def calculate_teacher_payment(self, month: datetime.date=None):
        if month:
            lessons = Lesson.objects.filter(
                date_start__gte=datetime.date(month.year, month.month, 1),
                date_start__lte=datetime.date(month.year, month.month, calendar.monthrange(month.year, month.month)[1]),
                group=self
            )
        else:
            lessons = Lesson.objects.filter(group=self)
        return sum([lesson.calc_teacher_payment() for lesson in lessons])

    def mm_calculate_payment_recommendation(self):
        teachers = list(self.teachers.all())
        t_p = 80 if len(teachers) == 0 else teachers[0].professionalism
        company = self.course.subject.company
        result = optimize_price(self.students.count(), self.course.complexity, t_p, company.C_t_min, company.C_s_min,
                                company.p_t_ser, company.p_s_ser)
        return result

    def when_is_next_lesson(self):
        planned_lessons = list(self.plannedlesson_set.all())
        dt = datetime.datetime.now()
        today_planned = [pl for pl in planned_lessons if pl.day==dt.weekday()+1 and pl.time_start >= dt.time()]
        if today_planned:
            return today_planned[0]

        dat = dt.date()
        for i in range(10):
            dat = dat + datetime.timedelta(days=1)
            planned = [pl for pl in planned_lessons if pl.day == dat.weekday() + 1]
            if planned:
                return planned[0]

    def __str__(self):
        return f"{self.name} ({self.course})"


class RoleUser(models.Model):
    company_user = models.ForeignKey(CompanyUser, on_delete=models.CASCADE)

    @property
    def userprofile(self):
        return self.company_user.userprofile

    class Meta:
        abstract = True

    def __str__(self):
        return f"{self.userprofile.user.username}"


class Student(RoleUser):
    groups = models.ManyToManyField(Group, blank=True, related_name='students')
    average_mark = models.IntegerField(default=0)  # необязательное поле для относительной оценки обучаемости студентов преподом
    presence_chance = models.IntegerField(default=100)  # 0 to 100

    def get_my_lessons_statistic_by_group(self, group):
        # FIXME: add date of start being in group checking
        lessons = group.lesson_set.all()
        be = 0
        total = 0
        for lesson in lessons:
            if lesson.present_students.filter(id=self.id).exists():
                be += 1
            total += 1

        return {'present': be, 'total': total}


class Teacher(RoleUser):
    groups = models.ManyToManyField(Group, related_name='teachers')  # учителей может быть больше одного
    courses = models.ManyToManyField(Course, blank=True, related_name='teachers')  # курсы которые ведет в этой компании
    rang = models.IntegerField(default=1)
    professionalism = models.IntegerField(default=50)

    def calc_salary_for_cur_month(self, company=None):
        if company is None:
            return sum([group.calculate_teacher_payment(datetime.date.today()) for group in self.groups.all()])
        else:
            return sum([group.calculate_teacher_payment(datetime.date.today()) for group in self.groups.filter(course__subject__company=company)])


class Admin(RoleUser):
    is_superadmin = models.BooleanField(default=False)


class PlannedLesson(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    time_start = models.TimeField()
    duration = models.IntegerField(default=90)  # у хвилинах
    day = models.IntegerField(default=1)

    days = {
        1: 'понеділок',
        2: 'вівторок',
        3: 'середа',
        4: 'четвер',
        5: 'п`ятниця',
        6: 'субота',
        7: 'неділя',
    }

    def __str__(self):
        return f"{self.days[self.day]} {self.time_start}  ({self.duration} m) - {self.group}"


def get_dates(days_numbers, start_date: datetime.date, end_date: datetime.date):
    while start_date <= end_date:
        if start_date.weekday() + 1 in days_numbers:
            yield start_date
        start_date += datetime.timedelta(days=1)


class Lesson(models.Model):
    time_start = models.TimeField()
    date_start = models.DateField()
    name = models.CharField(max_length=60)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    planned_lesson = models.ForeignKey(PlannedLesson, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    duration = models.IntegerField(default=90)
    present_students = models.ManyToManyField(Student, related_name='lessons')

    @classmethod
    def create_from_planed(cls, planned_lesson: PlannedLesson, date: datetime.date):
        return cls.objects.get_or_create(
            time_start=planned_lesson.time_start,
            date_start=date,
            planned_lesson=planned_lesson,
            group=planned_lesson.group,
            duration=planned_lesson.duration,
            defaults=dict(
                name='',
            )
        )[0]

    @classmethod
    def autogenerate_for_period(cls, group: Group, delta_from_now=datetime.timedelta(days=60)):
        planned_lessons = group.plannedlesson_set.all()
        today = datetime.date.today()
        planned_dict = {}
        for lesson in planned_lessons:
            planned_dict[lesson.day] = lesson
        dates = get_dates(list(planned_dict.keys()), today-delta_from_now, today)
        for date in dates:
            planned = planned_dict[date.weekday() + 1]
            lesson = cls.create_from_planed(planned, date)
            for student in group.students.all():
                if random.randint(1, 100) <= student.presence_chance:
                    lesson.present_students.add(student)

main/forms.py
from .models import *
from django import forms


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name', 'description']

    def save(self, company_id, commit=True):
        print('saving')
        self.instance.company_id = company_id
        super().save(commit)

main/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import *
from .forms import *
import plotly.graph_objs as go
from django.contrib.auth.decorators import login_required
from main.sub_views.admin import *
from main.sub_views.teacher import *
from main.sub_views.student import *
from .tools.functions import *


def subjects(request, id):
    comp_user = CompanyUser.objects.get(id=id)
    return render(request, 'subject_list.html', {'subjects': Subject.objects.filter(company=comp_user.company),
                                                 'comp_user': comp_user})


# Create your views here.
@login_required(login_url='/auth/sign_in')
def my_companies(request):
    companies_users = CompanyUser.objects.filter(userprofile=request.user.userprofile)
    companies_ids = set([company_user.company_id for company_user in companies_users])
    return render(request, 'my_companies.html', context={'companies': Company.objects.filter(id__in=companies_ids), 'comp_user': companies_users[0]})


def change_role(request, id):
    userprofile = request.user.userprofile
    comp_user = userprofile.active_company_user
    if not comp_user:
        return HttpResponse('You hadn`t pick company')
    userprofile.active_company_user = CompanyUser.objects.get(role_id=id, company_id=comp_user.company_id, userprofile=userprofile)
    userprofile.save()
    return redirect(f'/main/enter_company/{comp_user.company_id}')


def enter_company(request, id):
    comp_user = request.user.userprofile.active_company_user
    if not comp_user or comp_user.company_id != id:
        comp_user = request.user.userprofile.companyuser_set.filter(company_id=id)[0]
    role_name = comp_user.role.name

    request.user.userprofile.active_company_user = comp_user
    request.user.userprofile.save()

    return {
        'admin': company_admin,
        'teacher': company_teacher,
        'student': company_student,
    }[role_name](request, comp_user.id)


def company_teacher(request, comp_user_id):
    comp_user = CompanyUser.objects.get(id=comp_user_id)
    return HttpResponse('Сторінка поки не готова :(')

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>Document</title>
    {% endblock head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'CSS/sidebar.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
{% block styles %}{% endblock styles %}
<body>
{% include 'sidebar.html' %}
    <div class="content">
    {% block content %}
    
    {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
        // function on_company_change(index){
        //     window.location.href=`/main/reenter_company/${index}`;
        // }
    </script>
</body>
</html>

main/templates/company_admin.html
{% extends 'base.html' %}


{% block head %}
    <title>Company {{ company.name }}</title>
{% endblock %}

{% block styles %}
<style>
    a {
        text-decoration: none;
    }

    body {
        margin: 0px;
        padding: 0px;
    }

    .wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .company {
        display: flex;
        flex-direction: column;
        width: 70%;
        background-color: rgb(231, 255, 247);
        min-height: 800px;
        padding: 20px;
    }

    .money_data {
        margin: 30px 0px;
    }

    /* .money_data td,th {
        border: 1px solid black
    } */

    /* table {
        border-collapse: collapse;
    } */
</style>
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="company">
        <div class="companies">
            <h1 class="h1">{{ company.name }}</h1>
            <table class="money_data table">
                <tr>
                    <th scope="col"></th><th scope="col">Дохід</th><th scope="col">Витрати</th>
                </tr>
                <tr>
                    <th scope="row">Весь час</th><td>{{ company.calculate_income }}</td><td>{{ company.calculate_spends }}</td>
                </tr>
                <tr>
                    <th scope="row">Останній місяць</th><td>{{ company.calculate_income_last_month }}</td><td>{{ company.calculate_spends_last_month }}</td>
                </tr>
            </table>

            <div class="graph" style="width:600;height:500">
                {{ graph_html|safe }}
            </div>
            <!-- <p>Дохід: {{ company.calculate_income }}</p>
            <p>Витрати: {{ company.calculate_spends }}</p>
            <p>Дохід за останній місяць: {{ company.calculate_income_last_month }}</p>
            <p>Витрати за останній місяць:  {{ company.calculate_spends_last_month }}</p> -->
            
            <div class="buttons">
                <button class="btn btn-outline-success" onclick="window.location='{% url 'main:subjects' comp_user.id %}'">Предмети ({{ company.subject_set.count }})</button>
                <button class="btn btn-outline-success" onclick="window.location='{% url 'main:groups' comp_user.id %}'">Групи ({{ company.groups_amount }})</button>
                <button class='btn btn-outline-secondary'>Курси ({{ company.courses_amount }})</button>
                <button class="btn btn-outline-secondary">Студенти ({{ company.students_amount }})</button>
            </div>

            <button style="margin: 50px;" class="btn btn-outline-dark" onclick="window.location='{% url 'main:my_companies' %}'">Повернутися</button>
            <button class="btn btn-outline-success" onclick="window.location='/admin'">Адмін-панель</button>
        </div>
    </div>
</div>
{% endblock %}

main/templates/company_student.html
{% extends 'base.html' %}


{% block head %}
    <title>Company {{ company.name }}</title>
{% endblock %}


{% block styles %}
{% endblock %}


{% block content %}

{% endblock %}

main/templates/edit_subject.html
{% extends 'base.html' %}


{% block head %}
    <title>Edit subject</title>
{% endblock %}

{% block styles %}
<style>
  body {
        margin: 0px;
        padding: 0px;
    }

    .wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .company {
        display: flex;
        flex-direction: column;
        width: 70%;
        background-color: rgb(231, 255, 247);
        min-height: 800px;
        padding: 20px;
    }
</style>
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="company">
        
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-outline-success" type="submit" value="Зберегти">
            <!-- <button class="btn btn-outline-success" onclick="window.location='{% url 'main:create_subject' comp_user.id %}'">Зберегти</button> -->
        </form>
        <button class="btn btn-outline-danger" onclick="window.location='{% url 'main:delete_subject' comp_user.id subject.id%}'">Видалити</button>
        
    </div>
</div>
{% endblock %}

main/templates/groups.html
{% extends 'base.html' %}


{% block head %}
    <title>Groups of {{ company.name }}</title>
{% endblock %}

{% block styles %}
<style>
    a {
        color: inherit; /* blue colors for links too */
        text-decoration: inherit; /* no underline */
    }

    a:hover {
        color: inherit; /* blue colors for links too */
        text-decoration: inherit; /* no underline */
    }

    body {
        margin: 0px;
        padding: 0px;
    }

    .wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .company {
        display: flex;
        flex-direction: column;
        width: 70%;
        background-color: rgb(231, 255, 247);
        min-height: 800px;
        padding: 20px;
    }
    
    h1 {
        text-align: center;
    }

    .subject {
        border-radius: 10px;
        background-color: rgba(232, 255, 127, 0.514);
        min-height: 70px;
        margin: 20px;
        padding: 10px;
        transition: 0.5s;
    }

    .subject:hover {
        margin: 20px 30px;
        padding: 10px 20px;
        transition: 0.5s;
    }
</style>
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="company">
        <div class="groups">
            <h1 class="h1">Групи</h1>
            {% for group_dict in groups %}
                <div class="group">
                    <h3>{{ group_dict.group.name }}</h3>
                    <p>{{ group_dict.group.course }}</p>
                    <p>{{ group_dict.group.description }}</p>
                    <p>Всього зароблено: {{ group_dict.group.calculate_students_payment }}</p>
                    <p>Витрачено на зарплату: {{ group_dict.group.calculate_teacher_payment }}</p>
                    <p>Ціни, рекомандовані математичною моделлю:</p>
                    <p>Студент за годину: {{ group_dict.r_student }}</p>
                    <p>Викладачу за годину: {{ group_dict.r_teacher }}</p>

                    <div style="height: 500px; width: 100%">
                        {{ group_dict.graph_html|safe }}
                    </div>
                    
                    <table class="table">
                        <tr>
                            <th>Ім'я</th><th>Прізвище</th><th>Середня оцінка</th><th>Приєднався</th>
                        </tr>
                        {% for student_dict in group_dict.students %}
                            <tr>
                                <td>{{student_dict.userprofile.name}}</td><td>{{student_dict.userprofile.surname}}</td><td>{{student_dict.student.company_user.average_mark}}</td><td>{{student_dict.student.company_user.date_join}}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endfor %}
            <button class="btn btn-outline-success" onclick="window.location='{% url 'main:enter_company' comp_user.company_id %}'">Повернутися до компанії</button>
    
        </div>
    </div>
</div>
{% endblock %}

main/templates/my_companies.html
{% extends 'base.html' %}


{% block head %}
    <title>My companies</title>
{% endblock %}

{% block styles %}
<style>
    .companies {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .company {
        background-color: rgba(0, 255, 255, 0.295);
        border-radius: 10px;
        width: 70%;
        padding: 10px;
        margin: 10px;
    }

    a {
        text-decoration: none;
    }

    .company h1 {
        margin: 10px 35px;
        transition: 0.3s;
    }

    .company h1:hover {
        margin: 10px 55px;
        transition: 0.7s;
    }

    .company p {
        font-size: large;
        background-color: rgba(115, 224, 224, 0.164);
        padding: 10px;
        margin: 0px 10px;
        border-radius: 20px;
    }
</style>
{% endblock %}

{% block content %}
    <div class="companies">
        <h1>Доступні вам компанії:</h1>
        {% for company in companies %}
            <div class="company">
                <a href="{% url 'main:enter_company' company.id %}"> <h1>{{ company.name }}</h1> </a>
                <p>{{ company.description }}</p>
            </div>
        {% endfor %}
        <button class="btn btn-outline-success" onclick="window.location='/admin'">Адмін-панель</button>
    </div>
{% endblock %}

main/templates/sidebar.html
<div class="sidebar">
  <a class="active" href="#home">Home</a>
  <a href="#news">News</a>
  <a href="#contact">Contact</a>
  <a href="#about">About</a>
  <br>
  <div class="roles_panel">
    <p>Company: </p>
    <ul>
      {% for company in comp_user.userprofile.my_companies %}
          <li><a {% if company.selected %} style="background-color: #148a5fc3;;" {% endif %} href="/main/enter_company/{{ company.id }}"> {{ company.name }} </a></li>
      {% endfor %}
    </ul>
    <p>Role: </p>
    <ul>
      {% for role in comp_user.userprofile.available_roles %}
        <li><a {% if role.selected %} style="background-color: #148a5fc3;;" {% endif %}  href="/main/change_role/{{ role.id }}">{{ role.name }}</a></li>
      {% endfor %}
    </ul>
  </div>
</div>

main/templates/student_groups.html
{% extends 'base.html' %}


{% block head %}
    <title>Groups of {{ company.name }}</title>
{% endblock %}

{% block styles %}
<style>
    a {
        color: inherit; /* blue colors for links too */
        text-decoration: inherit; /* no underline */
    }

    a:hover {
        color: inherit; /* blue colors for links too */
        text-decoration: inherit; /* no underline */
    }

    body {
        margin: 0px;
        padding: 0px;
    }

    .wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .company {
        display: flex;
        flex-direction: column;
        width: 70%;
        background-color: rgb(231, 255, 247);
        min-height: 800px;
        padding: 20px;
    }

    h1 {
        text-align: center;
    }

    .subject {
        border-radius: 10px;
        background-color: rgba(232, 255, 127, 0.514);
        min-height: 70px;
        margin: 20px;
        padding: 10px;
        transition: 0.5s;
    }

    .subject:hover {
        margin: 20px 30px;
        padding: 10px 20px;
        transition: 0.5s;
    }
</style>
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="company">
        <div class="groups">
            <h1 class="h1">Групи</h1>
            {% for group in groups %}
                <div class="group">
                    <h3>{{ group.name }}</h3>
                    <p>{{ group.course }}</p>
                    <p>{{ group.description }}</p>
                    <p>Був присутній: {{ group.stat.present }}</p>
                    <p>Всього занять: {{ group.stat.total }}</p>

                    <div style="height: 500px; width: 100%">
                        {{ group.graph|safe }}
                    </div>

                    <p>Наступний запланований урок: {{ group.when_is_next_lesson }}</p>
                </div>
            {% endfor %}
            <button class="btn btn-outline-success" onclick="window.location='{% url 'main:enter_company' comp_user.company_id %}'">Повернутися до компанії</button>

        </div>
    </div>
</div>
{% endblock %}

main/templates/subject_list.html
{% extends 'base.html' %}


{% block head %}
    <title>Company {{ company.name }}</title>
{% endblock %}

{% block styles %}
<style>
    a {
        color: inherit; /* blue colors for links too */
        text-decoration: inherit; /* no underline */
    }

    a:hover {
        color: inherit; /* blue colors for links too */
        text-decoration: inherit; /* no underline */
    }

    body {
        margin: 0px;
        padding: 0px;
    }

    .wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .company {
        display: flex;
        flex-direction: column;
        width: 70%;
        background-color: rgb(231, 255, 247);
        min-height: 800px;
        padding: 20px;
    }
    
    h1 {
        text-align: center;
    }

    .subject {
        border-radius: 10px;
        background-color: rgba(232, 255, 127, 0.514);
        min-height: 70px;
        margin: 20px;
        padding: 10px;
        transition: 0.5s;
    }

    .subject:hover {
        margin: 20px 30px;
        padding: 10px 20px;
        transition: 0.5s;
    }
</style>
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="company">
        <div class="subjects">
            <h1 class="h1">Предмети</h1>
            {% for subject in subjects %}
                <a href="{% url 'main:edit_subject' comp_user.id subject.id %}">
                <div class="subject">
                    <h3>{{ subject.name }}</h3>
                    <p>{{ subject.description }}</p>
                </div>
                </a>
            {% endfor %}

            </div>
        <button class="btn btn-outline-success" onclick="window.location='{% url 'main:create_subject' comp_user.id %}'">Створити предмет</button>
        <button class="btn btn-outline-success" onclick="window.location='{% url 'main:enter_company' comp_user.id %}'">Повернутися до компанії</button>
    </div>
</div>
{% endblock %}